name = "Radium"
license = "GPL-3.0 License"
licenselink = "https://github.com/seasev/radium/blob/master/LICENSE.md"
description = "My personal Hugo theme based on Poison, which is in turn based on the Hyde theme for Jekyll."
min_version = "0.101.0"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/seasev/radium"

# If you have a running demo of the theme.
#demosite = "https://poison.lukeorth.com"

tags = ["blog", "personal", "dark", "dark-mode", "light", "minimal"]
features = ["blog", "katex", "table-of-contents", "tabs", "dark-mode", "series"]

[author]
    name = "Sean Williams"
    homepage = "https://seansev.com"

# If Porting existing theme
[original]
    author =  "Luke Orth"
    homepage = "http://lukeorth.com"
    repo = "https://www.github.com/lukeorth/poison"
